//! # DBus interface proxy for: `fi.w1.wpa_supplicant1.BSS`
//!
//! This code was generated by `zbus-xmlgen` `3.0.0` from DBus introspection data.
//! Source: `DBusWpaBss.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!

use zbus::dbus_proxy;

#[dbus_proxy(interface = "fi.w1.wpa_supplicant1.BSS")]
trait BSS {
    /// PropertiesChanged signal
    #[dbus_proxy(signal)]
    fn properties_changed(
        &self,
        properties: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// BSSID property
    #[dbus_proxy(property, name = "BSSID")]
    fn bssid(&self) -> zbus::Result<Vec<u8>>;

    /// Frequency property
    #[dbus_proxy(property)]
    fn frequency(&self) -> zbus::Result<u16>;

    /// SSID property
    #[dbus_proxy(property, name = "SSID")]
    fn ssid(&self) -> zbus::Result<Vec<u8>>;

    /// Signal property
    #[dbus_proxy(property)]
    fn signal(&self) -> zbus::Result<i16>;

    /// WPA property
    #[dbus_proxy(property, name = "WPA")]
    fn wpa(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;
}
