//! # D-Bus interface proxy for: `fi.w1.wpa_supplicant1.Interface`
//!
//! This code was generated by `zbus-xmlgen` `5.0.1` from D-Bus introspection data.
//! Source: `fi.w1.wpa_supplicant1.interface.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(interface = "fi.w1.wpa_supplicant1.Interface")]
pub trait Interface {
    /// AbortScan method
    fn abort_scan(&self) -> zbus::Result<()>;

    /// AddBlob method
    fn add_blob(&self, name: &str, data: &[u8]) -> zbus::Result<()>;

    /// AddNetwork method
    fn add_network(
        &self,
        args: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// AutoScan method
    fn auto_scan(&self, arg: &str) -> zbus::Result<()>;

    /// Disconnect method
    fn disconnect(&self) -> zbus::Result<()>;

    /// EAPLogoff method
    #[zbus(name = "EAPLogoff")]
    fn eaplogoff(&self) -> zbus::Result<()>;

    /// EAPLogon method
    #[zbus(name = "EAPLogon")]
    fn eaplogon(&self) -> zbus::Result<()>;

    /// FlushBSS method
    #[zbus(name = "FlushBSS")]
    fn flush_bss(&self, age: u32) -> zbus::Result<()>;

    /// GetBlob method
    fn get_blob(&self, name: &str) -> zbus::Result<Vec<u8>>;

    /// NetworkReply method
    fn network_reply(
        &self,
        path: &zbus::zvariant::ObjectPath<'_>,
        field: &str,
        value: &str,
    ) -> zbus::Result<()>;

    /// Reassociate method
    fn reassociate(&self) -> zbus::Result<()>;

    /// Reattach method
    fn reattach(&self) -> zbus::Result<()>;

    /// Reconnect method
    fn reconnect(&self) -> zbus::Result<()>;

    /// RemoveAllNetworks method
    fn remove_all_networks(&self) -> zbus::Result<()>;

    /// RemoveBlob method
    fn remove_blob(&self, name: &str) -> zbus::Result<()>;

    /// RemoveNetwork method
    fn remove_network(&self, path: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// Roam method
    fn roam(&self, addr: &str) -> zbus::Result<()>;

    /// SaveConfig method
    fn save_config(&self) -> zbus::Result<()>;

    /// Scan method
    fn scan(
        &self,
        args: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// SelectNetwork method
    fn select_network(&self, path: &zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// SetPKCS11EngineAndModulePath method
    #[zbus(name = "SetPKCS11EngineAndModulePath")]
    fn set_pkcs11engine_and_module_path(
        &self,
        pkcs11_engine_path: &str,
        pkcs11_module_path: &str,
    ) -> zbus::Result<()>;

    /// SignalPoll method
    fn signal_poll(
        &self,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// SubscribeProbeReq method
    fn subscribe_probe_req(&self) -> zbus::Result<()>;

    /// UnsubscribeProbeReq method
    fn unsubscribe_probe_req(&self) -> zbus::Result<()>;

    /// VendorElemAdd method
    fn vendor_elem_add(&self, frame_id: i32, ielems: &[u8]) -> zbus::Result<()>;

    /// VendorElemGet method
    fn vendor_elem_get(&self, frame_id: i32) -> zbus::Result<Vec<u8>>;

    /// VendorElemRem method
    fn vendor_elem_rem(&self, frame_id: i32, ielems: &[u8]) -> zbus::Result<()>;

    /// BSSAdded signal
    #[zbus(signal, name = "BSSAdded")]
    fn bssadded(
        &self,
        path: zbus::zvariant::ObjectPath<'_>,
        properties: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// BSSRemoved signal
    #[zbus(signal, name = "BSSRemoved")]
    fn bssremoved(&self, path: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// BlobAdded signal
    #[zbus(signal)]
    fn blob_added(&self, name: &str) -> zbus::Result<()>;

    /// BlobRemoved signal
    #[zbus(signal)]
    fn blob_removed(&self, name: &str) -> zbus::Result<()>;

    /// Certification signal
    #[zbus(signal)]
    fn certification(
        &self,
        certification: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// EAP signal
    #[zbus(signal, name = "EAP")]
    fn eap(&self, status: &str, parameter: &str) -> zbus::Result<()>;

    /// NetworkAdded signal
    #[zbus(signal)]
    fn network_added(
        &self,
        path: zbus::zvariant::ObjectPath<'_>,
        properties: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// NetworkRemoved signal
    #[zbus(signal)]
    fn network_removed(&self, path: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// NetworkRequest signal
    #[zbus(signal)]
    fn network_request(
        &self,
        path: zbus::zvariant::ObjectPath<'_>,
        field: &str,
        text: &str,
    ) -> zbus::Result<()>;

    /// NetworkSelected signal
    #[zbus(signal)]
    fn network_selected(&self, path: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// ProbeRequest signal
    #[zbus(signal)]
    fn probe_request(
        &self,
        args: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// PropertiesChanged signal
    #[zbus(signal)]
    fn properties_changed(
        &self,
        properties: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// ScanDone signal
    #[zbus(signal)]
    fn scan_done(&self, success: bool) -> zbus::Result<()>;

    /// StaAuthorized signal
    #[zbus(signal)]
    fn sta_authorized(&self, name: &str) -> zbus::Result<()>;

    /// StaDeauthorized signal
    #[zbus(signal)]
    fn sta_deauthorized(&self, name: &str) -> zbus::Result<()>;

    /// StationAdded signal
    #[zbus(signal)]
    fn station_added(
        &self,
        path: zbus::zvariant::ObjectPath<'_>,
        properties: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// StationRemoved signal
    #[zbus(signal)]
    fn station_removed(&self, path: zbus::zvariant::ObjectPath<'_>) -> zbus::Result<()>;

    /// AccessNetworkType property
    #[zbus(property)]
    fn access_network_type(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_access_network_type(&self, value: &str) -> zbus::Result<()>;

    /// ApAssocrespElements property
    #[zbus(property)]
    fn ap_assocresp_elements(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_ap_assocresp_elements(&self, value: &str) -> zbus::Result<()>;

    /// ApIsolate property
    #[zbus(property)]
    fn ap_isolate(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_ap_isolate(&self, value: &str) -> zbus::Result<()>;

    /// ApScan property
    #[zbus(property)]
    fn ap_scan(&self) -> zbus::Result<u32>;
    #[zbus(property)]
    fn set_ap_scan(&self, value: u32) -> zbus::Result<()>;

    /// ApVendorElements property
    #[zbus(property)]
    fn ap_vendor_elements(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_ap_vendor_elements(&self, value: &str) -> zbus::Result<()>;

    /// AssocStatusCode property
    #[zbus(property)]
    fn assoc_status_code(&self) -> zbus::Result<i32>;

    /// AuthStatusCode property
    #[zbus(property)]
    fn auth_status_code(&self) -> zbus::Result<i32>;

    /// AutoInterworking property
    #[zbus(property)]
    fn auto_interworking(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_auto_interworking(&self, value: &str) -> zbus::Result<()>;

    /// AutoUuid property
    #[zbus(property)]
    fn auto_uuid(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_auto_uuid(&self, value: &str) -> zbus::Result<()>;

    /// Autoscan property
    #[zbus(property)]
    fn autoscan(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_autoscan(&self, value: &str) -> zbus::Result<()>;

    /// BSSExpireAge property
    #[zbus(property, name = "BSSExpireAge")]
    fn bssexpire_age(&self) -> zbus::Result<u32>;
    #[zbus(property, name = "BSSExpireAge")]
    fn set_bssexpire_age(&self, value: u32) -> zbus::Result<()>;

    /// BSSExpireCount property
    #[zbus(property, name = "BSSExpireCount")]
    fn bssexpire_count(&self) -> zbus::Result<u32>;
    #[zbus(property, name = "BSSExpireCount")]
    fn set_bssexpire_count(&self, value: u32) -> zbus::Result<()>;

    /// BSSTMStatus property
    #[zbus(property, name = "BSSTMStatus")]
    fn bsstmstatus(&self) -> zbus::Result<u32>;

    /// BSSs property
    #[zbus(property, name = "BSSs")]
    fn bsss(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// BeaconInt property
    #[zbus(property)]
    fn beacon_int(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_beacon_int(&self, value: &str) -> zbus::Result<()>;

    /// Bgscan property
    #[zbus(property)]
    fn bgscan(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_bgscan(&self, value: &str) -> zbus::Result<()>;

    /// Blobs property
    #[zbus(property)]
    fn blobs(&self) -> zbus::Result<std::collections::HashMap<String, Vec<u8>>>;

    /// BridgeIfname property
    #[zbus(property)]
    fn bridge_ifname(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_bridge_ifname(&self, value: &str) -> zbus::Result<()>;

    /// BssMaxCount property
    #[zbus(property)]
    fn bss_max_count(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_bss_max_count(&self, value: &str) -> zbus::Result<()>;

    /// Capabilities property
    #[zbus(property)]
    fn capabilities(
        &self,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// CertInCb property
    #[zbus(property)]
    fn cert_in_cb(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_cert_in_cb(&self, value: &str) -> zbus::Result<()>;

    /// ColocIntfReporting property
    #[zbus(property)]
    fn coloc_intf_reporting(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_coloc_intf_reporting(&self, value: &str) -> zbus::Result<()>;

    /// ConfigFile property
    #[zbus(property)]
    fn config_file(&self) -> zbus::Result<String>;

    /// ConfigMethods property
    #[zbus(property)]
    fn config_methods(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_config_methods(&self, value: &str) -> zbus::Result<()>;

    /// Country property
    #[zbus(property)]
    fn country(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_country(&self, value: &str) -> zbus::Result<()>;

    /// CtrlInterface property
    #[zbus(property)]
    fn ctrl_interface(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_ctrl_interface(&self, value: &str) -> zbus::Result<()>;

    /// CtrlInterfaceGroup property
    #[zbus(property)]
    fn ctrl_interface_group(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_ctrl_interface_group(&self, value: &str) -> zbus::Result<()>;

    /// CurrentAuthMode property
    #[zbus(property)]
    fn current_auth_mode(&self) -> zbus::Result<String>;

    /// CurrentBSS property
    #[zbus(property, name = "CurrentBSS")]
    fn current_bss(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// CurrentNetwork property
    #[zbus(property)]
    fn current_network(&self) -> zbus::Result<zbus::zvariant::OwnedObjectPath>;

    /// DeviceName property
    #[zbus(property)]
    fn device_name(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_device_name(&self, value: &str) -> zbus::Result<()>;

    /// DeviceType property
    #[zbus(property)]
    fn device_type(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_device_type(&self, value: &str) -> zbus::Result<()>;

    /// DisableScanOffload property
    #[zbus(property)]
    fn disable_scan_offload(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_disable_scan_offload(&self, value: &str) -> zbus::Result<()>;

    /// DisassocLowAck property
    #[zbus(property)]
    fn disassoc_low_ack(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_disassoc_low_ack(&self, value: &str) -> zbus::Result<()>;

    /// DisconnectReason property
    #[zbus(property)]
    fn disconnect_reason(&self) -> zbus::Result<i32>;

    /// Dot11RSNAConfigPMKLifetime property
    #[zbus(property, name = "Dot11RSNAConfigPMKLifetime")]
    fn dot11_rsnaconfig_pmklifetime(&self) -> zbus::Result<String>;
    #[zbus(property, name = "Dot11RSNAConfigPMKLifetime")]
    fn set_dot11_rsnaconfig_pmklifetime(&self, value: &str) -> zbus::Result<()>;

    /// Dot11RSNAConfigPMKReauthThreshold property
    #[zbus(property, name = "Dot11RSNAConfigPMKReauthThreshold")]
    fn dot11_rsnaconfig_pmkreauth_threshold(&self) -> zbus::Result<String>;
    #[zbus(property, name = "Dot11RSNAConfigPMKReauthThreshold")]
    fn set_dot11_rsnaconfig_pmkreauth_threshold(&self, value: &str) -> zbus::Result<()>;

    /// Dot11RSNAConfigSATimeout property
    #[zbus(property, name = "Dot11RSNAConfigSATimeout")]
    fn dot11_rsnaconfig_satimeout(&self) -> zbus::Result<String>;
    #[zbus(property, name = "Dot11RSNAConfigSATimeout")]
    fn set_dot11_rsnaconfig_satimeout(&self, value: &str) -> zbus::Result<()>;

    /// Driver property
    #[zbus(property)]
    fn driver(&self) -> zbus::Result<String>;

    /// DriverParam property
    #[zbus(property)]
    fn driver_param(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_driver_param(&self, value: &str) -> zbus::Result<()>;

    /// DtimPeriod property
    #[zbus(property)]
    fn dtim_period(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_dtim_period(&self, value: &str) -> zbus::Result<()>;

    /// EapolVersion property
    #[zbus(property)]
    fn eapol_version(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_eapol_version(&self, value: &str) -> zbus::Result<()>;

    /// ExtPasswordBackend property
    #[zbus(property)]
    fn ext_password_backend(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_ext_password_backend(&self, value: &str) -> zbus::Result<()>;

    /// ExternalSim property
    #[zbus(property)]
    fn external_sim(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_external_sim(&self, value: &str) -> zbus::Result<()>;

    /// FastReauth property
    #[zbus(property)]
    fn fast_reauth(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_fast_reauth(&self, value: bool) -> zbus::Result<()>;

    /// FilterRssi property
    #[zbus(property)]
    fn filter_rssi(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_filter_rssi(&self, value: &str) -> zbus::Result<()>;

    /// FilterSsids property
    #[zbus(property)]
    fn filter_ssids(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_filter_ssids(&self, value: &str) -> zbus::Result<()>;

    /// FreqList property
    #[zbus(property)]
    fn freq_list(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_freq_list(&self, value: &str) -> zbus::Result<()>;

    /// FtmInitiator property
    #[zbus(property)]
    fn ftm_initiator(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_ftm_initiator(&self, value: &str) -> zbus::Result<()>;

    /// FtmResponder property
    #[zbus(property)]
    fn ftm_responder(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_ftm_responder(&self, value: &str) -> zbus::Result<()>;

    /// GasAddress3 property
    #[zbus(property)]
    fn gas_address3(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_gas_address3(&self, value: &str) -> zbus::Result<()>;

    /// GasRandAddrLifetime property
    #[zbus(property)]
    fn gas_rand_addr_lifetime(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_gas_rand_addr_lifetime(&self, value: &str) -> zbus::Result<()>;

    /// GasRandMacAddr property
    #[zbus(property)]
    fn gas_rand_mac_addr(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_gas_rand_mac_addr(&self, value: &str) -> zbus::Result<()>;

    /// GoAccessNetworkType property
    #[zbus(property)]
    fn go_access_network_type(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_go_access_network_type(&self, value: &str) -> zbus::Result<()>;

    /// GoInternet property
    #[zbus(property)]
    fn go_internet(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_go_internet(&self, value: &str) -> zbus::Result<()>;

    /// GoInterworking property
    #[zbus(property)]
    fn go_interworking(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_go_interworking(&self, value: &str) -> zbus::Result<()>;

    /// GoVenueGroup property
    #[zbus(property)]
    fn go_venue_group(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_go_venue_group(&self, value: &str) -> zbus::Result<()>;

    /// GoVenueType property
    #[zbus(property)]
    fn go_venue_type(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_go_venue_type(&self, value: &str) -> zbus::Result<()>;

    /// Hessid property
    #[zbus(property)]
    fn hessid(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_hessid(&self, value: &str) -> zbus::Result<()>;

    /// Ifname property
    #[zbus(property)]
    fn ifname(&self) -> zbus::Result<String>;

    /// IgnoreOldScanRes property
    #[zbus(property)]
    fn ignore_old_scan_res(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_ignore_old_scan_res(&self, value: &str) -> zbus::Result<()>;

    /// InitialFreqList property
    #[zbus(property)]
    fn initial_freq_list(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_initial_freq_list(&self, value: &str) -> zbus::Result<()>;

    /// Interworking property
    #[zbus(property)]
    fn interworking(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_interworking(&self, value: &str) -> zbus::Result<()>;

    /// KeyMgmtOffload property
    #[zbus(property)]
    fn key_mgmt_offload(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_key_mgmt_offload(&self, value: &str) -> zbus::Result<()>;

    /// MACAddressRandomizationMask property
    #[zbus(property, name = "MACAddressRandomizationMask")]
    fn macaddress_randomization_mask(
        &self,
    ) -> zbus::Result<std::collections::HashMap<String, Vec<u8>>>;
    #[zbus(property, name = "MACAddressRandomizationMask")]
    fn set_macaddress_randomization_mask(
        &self,
        value: std::collections::HashMap<&str, &[u8]>,
    ) -> zbus::Result<()>;

    /// MacAddr property
    #[zbus(property)]
    fn mac_addr(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_mac_addr(&self, value: &str) -> zbus::Result<()>;

    /// Manufacturer property
    #[zbus(property)]
    fn manufacturer(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_manufacturer(&self, value: &str) -> zbus::Result<()>;

    /// MaxNumSta property
    #[zbus(property)]
    fn max_num_sta(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_max_num_sta(&self, value: &str) -> zbus::Result<()>;

    /// ModelName property
    #[zbus(property)]
    fn model_name(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_model_name(&self, value: &str) -> zbus::Result<()>;

    /// ModelNumber property
    #[zbus(property)]
    fn model_number(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_model_number(&self, value: &str) -> zbus::Result<()>;

    /// Networks property
    #[zbus(property)]
    fn networks(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// Okc property
    #[zbus(property)]
    fn okc(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_okc(&self, value: &str) -> zbus::Result<()>;

    /// OpenscEnginePath property
    #[zbus(property)]
    fn opensc_engine_path(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_opensc_engine_path(&self, value: &str) -> zbus::Result<()>;

    /// OpensslCiphers property
    #[zbus(property)]
    fn openssl_ciphers(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_openssl_ciphers(&self, value: &str) -> zbus::Result<()>;

    /// OsVersion property
    #[zbus(property)]
    fn os_version(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_os_version(&self, value: &str) -> zbus::Result<()>;

    /// OsuDir property
    #[zbus(property)]
    fn osu_dir(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_osu_dir(&self, value: &str) -> zbus::Result<()>;

    /// P2pGoMaxInactivity property
    #[zbus(property)]
    fn p2p_go_max_inactivity(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_p2p_go_max_inactivity(&self, value: &str) -> zbus::Result<()>;

    /// P2pSearchDelay property
    #[zbus(property)]
    fn p2p_search_delay(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_p2p_search_delay(&self, value: &str) -> zbus::Result<()>;

    /// PKCS11EnginePath property
    #[zbus(property, name = "PKCS11EnginePath")]
    fn pkcs11engine_path(&self) -> zbus::Result<String>;

    /// PKCS11ModulePath property
    #[zbus(property, name = "PKCS11ModulePath")]
    fn pkcs11module_path(&self) -> zbus::Result<String>;

    /// PassiveScan property
    #[zbus(property)]
    fn passive_scan(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_passive_scan(&self, value: &str) -> zbus::Result<()>;

    /// PbcInM1 property
    #[zbus(property)]
    fn pbc_in_m1(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_pbc_in_m1(&self, value: &str) -> zbus::Result<()>;

    /// PcscPin property
    #[zbus(property)]
    fn pcsc_pin(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_pcsc_pin(&self, value: &str) -> zbus::Result<()>;

    /// PcscReader property
    #[zbus(property)]
    fn pcsc_reader(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_pcsc_reader(&self, value: &str) -> zbus::Result<()>;

    /// Pmf property
    #[zbus(property)]
    fn pmf(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_pmf(&self, value: &str) -> zbus::Result<()>;

    /// PreassocMacAddr property
    #[zbus(property)]
    fn preassoc_mac_addr(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_preassoc_mac_addr(&self, value: &str) -> zbus::Result<()>;

    /// RandAddrLifetime property
    #[zbus(property)]
    fn rand_addr_lifetime(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_rand_addr_lifetime(&self, value: &str) -> zbus::Result<()>;

    /// ReassocSameBssOptim property
    #[zbus(property)]
    fn reassoc_same_bss_optim(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_reassoc_same_bss_optim(&self, value: &str) -> zbus::Result<()>;

    /// RoamComplete property
    #[zbus(property)]
    fn roam_complete(&self) -> zbus::Result<bool>;

    /// RoamTime property
    #[zbus(property)]
    fn roam_time(&self) -> zbus::Result<u32>;

    /// SaeGroups property
    #[zbus(property)]
    fn sae_groups(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_sae_groups(&self, value: &str) -> zbus::Result<()>;

    /// SaePmkidInAssoc property
    #[zbus(property)]
    fn sae_pmkid_in_assoc(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_sae_pmkid_in_assoc(&self, value: &str) -> zbus::Result<()>;

    /// SaePwe property
    #[zbus(property)]
    fn sae_pwe(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_sae_pwe(&self, value: &str) -> zbus::Result<()>;

    /// ScanCurFreq property
    #[zbus(property)]
    fn scan_cur_freq(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_scan_cur_freq(&self, value: &str) -> zbus::Result<()>;

    /// ScanInterval property
    #[zbus(property)]
    fn scan_interval(&self) -> zbus::Result<i32>;
    #[zbus(property)]
    fn set_scan_interval(&self, value: i32) -> zbus::Result<()>;

    /// ScanResValidForConnect property
    #[zbus(property)]
    fn scan_res_valid_for_connect(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_scan_res_valid_for_connect(&self, value: &str) -> zbus::Result<()>;

    /// Scanning property
    #[zbus(property)]
    fn scanning(&self) -> zbus::Result<bool>;

    /// SchedScanInterval property
    #[zbus(property)]
    fn sched_scan_interval(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_sched_scan_interval(&self, value: &str) -> zbus::Result<()>;

    /// SchedScanPlans property
    #[zbus(property)]
    fn sched_scan_plans(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_sched_scan_plans(&self, value: &str) -> zbus::Result<()>;

    /// SchedScanStartDelay property
    #[zbus(property)]
    fn sched_scan_start_delay(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_sched_scan_start_delay(&self, value: &str) -> zbus::Result<()>;

    /// SerialNumber property
    #[zbus(property)]
    fn serial_number(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_serial_number(&self, value: &str) -> zbus::Result<()>;

    /// SessionLength property
    #[zbus(property)]
    fn session_length(&self) -> zbus::Result<u32>;

    /// State property
    #[zbus(property)]
    fn state(&self) -> zbus::Result<String>;

    /// Stations property
    #[zbus(property)]
    fn stations(&self) -> zbus::Result<Vec<zbus::zvariant::OwnedObjectPath>>;

    /// TdlsExternalControl property
    #[zbus(property)]
    fn tdls_external_control(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_tdls_external_control(&self, value: &str) -> zbus::Result<()>;

    /// UpdateConfig property
    #[zbus(property)]
    fn update_config(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_update_config(&self, value: &str) -> zbus::Result<()>;

    /// Uuid property
    #[zbus(property)]
    fn uuid(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_uuid(&self, value: &str) -> zbus::Result<()>;

    /// WowlanDisconnectOnDeinit property
    #[zbus(property)]
    fn wowlan_disconnect_on_deinit(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_wowlan_disconnect_on_deinit(&self, value: &str) -> zbus::Result<()>;

    /// WowlanTriggers property
    #[zbus(property)]
    fn wowlan_triggers(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_wowlan_triggers(&self, value: &str) -> zbus::Result<()>;

    /// WpaRscRelaxation property
    #[zbus(property)]
    fn wpa_rsc_relaxation(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_wpa_rsc_relaxation(&self, value: &str) -> zbus::Result<()>;

    /// WpsCredAddSae property
    #[zbus(property)]
    fn wps_cred_add_sae(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_wps_cred_add_sae(&self, value: &str) -> zbus::Result<()>;

    /// WpsCredProcessing property
    #[zbus(property)]
    fn wps_cred_processing(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_wps_cred_processing(&self, value: &str) -> zbus::Result<()>;

    /// WpsNfcDevPw property
    #[zbus(property)]
    fn wps_nfc_dev_pw(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_wps_nfc_dev_pw(&self, value: &str) -> zbus::Result<()>;

    /// WpsNfcDevPwId property
    #[zbus(property)]
    fn wps_nfc_dev_pw_id(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_wps_nfc_dev_pw_id(&self, value: &str) -> zbus::Result<()>;

    /// WpsNfcDhPrivkey property
    #[zbus(property)]
    fn wps_nfc_dh_privkey(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_wps_nfc_dh_privkey(&self, value: &str) -> zbus::Result<()>;

    /// WpsNfcDhPubkey property
    #[zbus(property)]
    fn wps_nfc_dh_pubkey(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_wps_nfc_dh_pubkey(&self, value: &str) -> zbus::Result<()>;

    /// WpsPriority property
    #[zbus(property)]
    fn wps_priority(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_wps_priority(&self, value: &str) -> zbus::Result<()>;

    /// WpsVendorExtM1 property
    #[zbus(property)]
    fn wps_vendor_ext_m1(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_wps_vendor_ext_m1(&self, value: &str) -> zbus::Result<()>;
}

/*
//! # D-Bus interface proxy for: `fi.w1.wpa_supplicant1.Interface.WPS`
//!
//! This code was generated by `zbus-xmlgen` `5.0.1` from D-Bus introspection data.
//! Source: `fi.w1.wpa_supplicant1.interface.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the [Writing a client proxy] section of the zbus
//! documentation.
//!
//! This type implements the [D-Bus standard interfaces], (`org.freedesktop.DBus.*`) for which the
//! following zbus API can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! Consequently `zbus-xmlgen` did not generate code for the above interfaces.
//!
//! [Writing a client proxy]: https://dbus2.github.io/zbus/client.html
//! [D-Bus standard interfaces]: https://dbus.freedesktop.org/doc/dbus-specification.html#standard-interfaces,
use zbus::proxy;
#[proxy(
    interface = "fi.w1.wpa_supplicant1.Interface.WPS",
    assume_defaults = true
)]
pub trait WPS {
    /// Cancel method
    fn cancel(&self) -> zbus::Result<()>;

    /// Start method
    fn start(
        &self,
        args: std::collections::HashMap<&str, &zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// Credentials signal
    #[zbus(signal)]
    fn credentials(
        &self,
        credentials: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// Event signal
    #[zbus(signal)]
    fn event(
        &self,
        name: &str,
        args: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// PropertiesChanged signal
    #[zbus(signal)]
    fn properties_changed(
        &self,
        properties: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// ConfigMethods property
    #[zbus(property)]
    fn config_methods(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_config_methods(&self, value: &str) -> zbus::Result<()>;

    /// DeviceName property
    #[zbus(property)]
    fn device_name(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_device_name(&self, value: &str) -> zbus::Result<()>;

    /// DeviceType property
    #[zbus(property)]
    fn device_type(&self) -> zbus::Result<Vec<u8>>;
    #[zbus(property)]
    fn set_device_type(&self, value: &[u8]) -> zbus::Result<()>;

    /// Manufacturer property
    #[zbus(property)]
    fn manufacturer(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_manufacturer(&self, value: &str) -> zbus::Result<()>;

    /// ModelName property
    #[zbus(property)]
    fn model_name(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_model_name(&self, value: &str) -> zbus::Result<()>;

    /// ModelNumber property
    #[zbus(property)]
    fn model_number(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_model_number(&self, value: &str) -> zbus::Result<()>;

    /// ProcessCredentials property
    #[zbus(property)]
    fn process_credentials(&self) -> zbus::Result<bool>;
    #[zbus(property)]
    fn set_process_credentials(&self, value: bool) -> zbus::Result<()>;

    /// SerialNumber property
    #[zbus(property)]
    fn serial_number(&self) -> zbus::Result<String>;
    #[zbus(property)]
    fn set_serial_number(&self, value: &str) -> zbus::Result<()>;
}
*/
