//! # DBus interface proxy for: `fi.w1.wpa_supplicant1.BSS`
//!
//! This code was generated by `zbus-xmlgen` `3.0.0` from DBus introspection data.
//! Source: `fi.w1.wpa_supplicant1.bss.xml`.
//!
//! You may prefer to adapt it, instead of using it verbatim.
//!
//! More information can be found in the
//! [Writing a client proxy](https://dbus.pages.freedesktop.org/zbus/client.html)
//! section of the zbus documentation.
//!
//! This DBus object implements
//! [standard DBus interfaces](https://dbus.freedesktop.org/doc/dbus-specification.html),
//! (`org.freedesktop.DBus.*`) for which the following zbus proxies can be used:
//!
//! * [`zbus::fdo::IntrospectableProxy`]
//! * [`zbus::fdo::PropertiesProxy`]
//!
//! …consequently `zbus-xmlgen` did not generate code for the above interfaces.

use zbus::dbus_proxy;

#[dbus_proxy(interface = "fi.w1.wpa_supplicant1.BSS")]
trait BSS {
    /// PropertiesChanged signal
    #[dbus_proxy(signal)]
    fn properties_changed(
        &self,
        properties: std::collections::HashMap<&str, zbus::zvariant::Value<'_>>,
    ) -> zbus::Result<()>;

    /// Age property
    #[dbus_proxy(property)]
    fn age(&self) -> zbus::Result<u32>;

    /// BSSID property
    #[dbus_proxy(property, name = "BSSID")]
    fn bssid(&self) -> zbus::Result<Vec<u8>>;

    /// Frequency property
    #[dbus_proxy(property)]
    fn frequency(&self) -> zbus::Result<u16>;

    /// IEs property
    #[dbus_proxy(property, name = "IEs")]
    fn ies(&self) -> zbus::Result<Vec<u8>>;

    /// Mode property
    #[dbus_proxy(property)]
    fn mode(&self) -> zbus::Result<String>;

    /// Privacy property
    #[dbus_proxy(property)]
    fn privacy(&self) -> zbus::Result<bool>;

    /// RSN property
    #[dbus_proxy(property, name = "RSN")]
    fn rsn(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// Rates property
    #[dbus_proxy(property)]
    fn rates(&self) -> zbus::Result<Vec<u32>>;

    /// SSID property
    #[dbus_proxy(property, name = "SSID")]
    fn ssid(&self) -> zbus::Result<Vec<u8>>;

    /// Signal property
    #[dbus_proxy(property)]
    fn signal(&self) -> zbus::Result<i16>;

    /// WPA property
    #[dbus_proxy(property, name = "WPA")]
    fn wpa(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;

    /// WPS property
    #[dbus_proxy(property, name = "WPS")]
    fn wps(&self) -> zbus::Result<std::collections::HashMap<String, zbus::zvariant::OwnedValue>>;
}
